#!/bin/bash
declare -a ZIGTARGETS=(
    'x86_64-linux-musl'
    'aarch64-linux-musl'
)
#arm-linux-musleabihf ## 32 bit arm
ZIGBIN="$PWD/zig-cc"
export CC="$ZIGBIN/cc"
export CXX="$ZIGBIN/cxx"
export AR="$ZIGBIN/ar"
export LD="$ZIGBIN/ld"
export RANLIB="$ZIGBIN/ranlib"

for Target in "${ZIGTARGETS[@]}";
do
  export ZIGTARGET=$Target
  echo "============ $ZIGTARGET ============"
  make zig
done

